<?php

/**
 * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\authex\module\mapper\userManagementMapper
 * @date 2015-08-18 16:31:45
 *
 * @author Dmitry Emelyanov <gilberg.vrn@gmail.com>
 */
\mpcmf\system\configuration\config::setConfig(__FILE__, [
    'storage' => [
        'configSection' => 'default',
        'db' => 'authex',
        'collection' => 'userManager'
    ]
]);