<?php

/**
 * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\api\module\mapper\tokenMapper
 * @date 2015-08-17 15:33:33
 *
 * @author Dmitry Emelyanov <gilberg.vrn@gmail.com>
 */
\mpcmf\system\configuration\config::setConfig(__FILE__, [
    'storage' => [
        'configSection' => 'default',
        'db' => 'authex',
        'collection' => 'token'
    ]
]);