<?php
/**
 * @generated by mpcmf/codeManager
 *
 * @package mpcmf\modules\authex\module\mapper\inviteMapper
 * @date 2015-10-01 12:35:13
 *
 * @author Dmitry Emelyanov <gilberg.vrn@gmail.com>
 */
\mpcmf\system\configuration\config::setConfig(__FILE__, [
    'storage' => [
        'configSection' => 'default',
        'db' => 'authex',
        'collection' => 'invite'
    ]
]);